### ISSUE TITLE
bug: devture_traefik_certs_dumper_container_extra_arguments added as entrypoint arguments, not docker run arguments

### ISSUE THREAD

**Issue by patrickstump** [devture/com.devture.ansible.role.traefik_certs_dumper#2]
With the other devture roles, each role has a variable ending in "container_extra_arguments", which are meant to add extra options when running the `docker run` command.  This aids in adding custom features for things like `log_driver` and `log_options`.

For this role the variable is `devture_traefik_certs_dumper_container_extra_arguments`.

This role is using this variable in [templates/bin/entrypoint.sh](https://github.com/devture/com.devture.ansible.role.traefik_certs_dumper/blob/ad3f00ba0968fb75a80df30cddac7ab11b7b0a5f/templates/bin/entrypoint.sh#L19) as an option to the `/usr/bin/traefik-certs-dumper` program.

It instead needs to be added to  [templates/systemd/devture-traefik-certs-dumper.service.j2](https://github.com/devture/com.devture.ansible.role.traefik_certs_dumper/blob/ad3f00ba0968fb75a80df30cddac7ab11b7b0a5f/templates/systemd/devture-traefik-certs-dumper.service.j2#L32)  and [templates/systemd/devture-traefik-certs-dumper-wait-for-domain@.service.j2](https://github.com/devture/com.devture.ansible.role.traefik_certs_dumper/blob/ad3f00ba0968fb75a80df30cddac7ab11b7b0a5f/templates/systemd/devture-traefik-certs-dumper-wait-for-domain%40.service.j2#L25) like the example below :

templates/systemd/devture-traefik-certs-dumper.service.j2
```
ExecStart={{ devture_systemd_docker_base_host_command_docker }} run \
			--rm \
			--name={{ devture_traefik_certs_dumper_identifier }} \
			--log-driver=none \
			--mount type=bind,src={{ devture_traefik_certs_dumper_bin_dir_path }},dst=/certs-dumper-bin,ro \
			--mount type=bind,src={{ devture_traefik_certs_dumper_ssl_dir_path }},dst=/in,ro \
			--mount type=bind,src={{ devture_traefik_certs_dumper_dumped_certificates_dir_path }},dst=/out \
			--tmpfs=/intermediate:rw,noexec,nosuid,size=100m \
			--tmpfs=/staging:rw,noexec,nosuid,size=100m \
			--entrypoint=/bin/sh \
			{{ devture_traefik_certs_dumper_container_image }} \
			/certs-dumper-bin/entrypoint.sh
                         {% if devture_traefik_certs_dumper_container_extra_arguments | length > 0 %}
			{{ devture_traefik_certs_dumper_container_extra_arguments | join(" ") }} \
			{% endif %}
```

templates/systemd/devture-traefik-certs-dumper-wait-for-domain@.service.j2
```
ExecStart={{ devture_systemd_docker_base_host_command_docker }} run \
			--rm \
			--log-driver=none \
			--mount type=bind,src={{ devture_traefik_certs_dumper_bin_dir_path }},dst=/certs-dumper-bin,ro \
			--mount type=bind,src={{ devture_traefik_certs_dumper_dumped_certificates_dir_path }},dst={{ 
                         devture_traefik_certs_dumper_dumped_certificates_dir_path }},ro \
			--entrypoint=/bin/sh \
			{{ devture_traefik_certs_dumper_container_image }} \
			-c '/certs-dumper-bin/wait-for-domain.sh %i'
			{% if devture_traefik_certs_dumper_container_extra_arguments | length > 0 %}
			{{ devture_traefik_certs_dumper_container_extra_arguments | join(" ") }} \
			{% endif %}
```

and remove it from [templates/bin/entrypoint.sh](https://github.com/devture/com.devture.ansible.role.traefik_certs_dumper/blob/ad3f00ba0968fb75a80df30cddac7ab11b7b0a5f/templates/bin/entrypoint.sh#L19) and replace it with a new variable.

```bash
/certs-dumper-bin/wait-for-file.sh /in/{{ devture_traefik_certs_dumper_ssl_acme_file_name }} \
&& \
/usr/bin/traefik-certs-dumper file \
--version v2 \
--source /in/{{ devture_traefik_certs_dumper_ssl_acme_file_name }} \
--dest /intermediate \
--watch \
--post-hook "{{ devture_traefik_certs_dumper_container_post_hook }}" \
--domain-subdir {{ devture_traefik_certs_dumper_container_extra_arguments | join(" ") }}
```

> This might be a breaking change if some have been using this for the domain-subdir. A new variable should be created.

**Comment by spantaleev** [comment]
You're right! The variable is misnamed with regard to what we've been using it for.

---

That said, it's not actually used for `--domain-subdir`. It's expanded merely after `--domain-subdir`, as a simple way to "pass extra arguments".

---

Still, this may be a breaking change. I think few people are using this role variable anyway, so maybe it's not worth mentioning it in the changelog. If this proves to be incorrect, we may do it.
